// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CitiesSelectController from "./cities_select_controller"
application.register("cities-select", CitiesSelectController)
